[features]
seeds = true

[programs.devnet]
ember_bed = "BW2w1qyVvgZyv6iNuYycWDnmNCMHoY8iA49BkHPzPi7Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/proto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
