[features]
seeds = true

[programs.devnet]
ember_bed = "7qVqnQbVgsYVE8pysemgphSTNX7WmbBvk3CUf4PcA5qj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/proto/PhoenixProj/Wallets/PrjctTokenAuthority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
